[project]
name = "mmalecki-things"
version = "0.0.0"
authors = [
    { name = "Maciej Małecki", email = "me@mmalecki.com" },
]
license = "MIT"
dependencies = [
    "build123d>=0.11.1",
    "cadquery>=2.8.0",
    "cq-queryabolt>=0.1.2",
    "ocp-vscode>=3.4.0",
]

[project.urls]
Repository = "https://github.com/mmalecki/things"
